apiVersion: apps/v1
kind: Deployment
metadata: 
  name: tomcat-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat-app
  template: 
    metadata:
      labels: 
        app: tomcat-app
    spec:
      containers:
      - name: tomcat-app
        image: guru6910/guru:v2
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service 
metadata: 
  name: tomcat-service 
spec:
  selector:
    app: tomcat-app
  ports:
  - name: tomcat
    targetPort: 18
    port: 8080
  type: LoadBalancer
